### ISSUE TITLE
Terraform dashboard fails with metric widget

### ISSUE THREAD

**Issue by nathanschile** [newrelic/newrelic-cli#1052]
### Description

I'm attempting to migrate my terraform `newrelic_dashboard` resources to `newrelic_one_dashboard` resources, https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/migration_guide_newrelic_dashboard When I run the `newrelic utils terraform dashboard` command it fails with `FATAL failed unmarshaling rawConfiguration for widget "DB Circuit Breaker" of type "widget_line"`

### Go Version
newrelic version 0.33.0

### Current behavior
`newrelic utils terraform dashboard` command fails with `FATAL failed unmarshaling rawConfiguration for widget "DB Circuit Breaker" of type "widget_line"`

### Expected behavior
I expect it to generate the HCL for the `newrelic_one_dashboard` resource

### Steps To Reproduce
1. Have a widget defined in your dashboard JSON.
```
...
        {
          "id": "123",
          "layout": {
            "column": 9,
            "height": 3,
            "row": 10,
            "width": 4
          },
          "rawConfiguration": {
            "accountId": 123,
            "compareWith": [],
            "duration": 1800000,
            "entityIds": [
              123
            ],
            "facet": "host",
            "metrics": [
              {
                "name": "JMX/metrics/gauges/Database.circuitBreakerState/Value",
                "values": [
                  "average_value"
                ]
              }
            ],
            "rawMetricName": "JMX/metrics/gauges/Database.circuitBreakerState/Value"
          },
          "title": "DB Circuit Breaker",
          "visualization": {
            "id": "viz.line"
          }
        }
...
```
2. Run the command to generate the newrelic_one_dashboard resource, `newrelic utils terraform dashboard`
3. See error, `FATAL failed unmarshaling rawConfiguration for widget "DB Circuit Breaker" of type "widget_line" `

**Comment by FuyuanChu** [comment]
same problem when trying to migrate resource `newrelic_dashboard` to `newrelic_one_dashboard`.
