### ISSUE TITLE
Common variable naming pattern/convention for commands and subcommand

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-cli#110]
### Objective
Create a common naming pattern/convention for commands and subcommands to facilitate better associations and understanding of command hierarchy.

#### Current patterns in codebase:
- `completionCmd` (newrelic)
- `versionCmd` (newrelic)
- `apmApplication` (apm)
- `entitiesSearch` (entities)
- `queryCmd` (nerdgraph)
- `credentialsAdd` (credentials)
- `cmdSet` (config)
- `cmdGet` (config)

#### Proposed patterns (1:1 mapping with above)
Format (top-level commands): `cmd<CommandName>`
Format (sub-commands): `cmd<CommandName><SubcommandName>`

**Commands**
- `cmdCompletion`
- `cmdVersion`

**Sub-commands**
- `cmdApplicationsGet`
- `cmdEntitySearch`
- `cmdNerdGraphQuery`
- `cmdCredentialsAdd`
- `cmdConfigSet`
- `cmdConfigGet`

#### Naming convention for associated functions that could do work for a command
- `applicationsGet` would do work for `cmdApplicationsGet`
- `entitySearch` would do work for `cmdEntitySearch`
- ...etc, etc

### Acceptance Criteria
- Agreement on a common pattern/naming convention for commands and subcommand variables
    - **Update:** The pattern above has been approved 
- Variables have been updated in the code to reflect agreed upon pattern

**Comment by ctrombley** [comment]
Resolved by #114 .
