### ISSUE TITLE
S3 bucket isn't browseable

### ISSUE THREAD

**Issue by grepory** [newrelic/newrelic-cli#1251]
### Description
The README states:

```
Pre-built binaries are available for all of the above platforms. You can download the latest releases [here](https://download.newrelic.com/install/newrelic-cli).
```

But the S3 bucket where these reside isn't browsable. You can see all of the versions that are available, but when you click on a link to, say, [the latest version](https://download.newrelic.com/install/v0.43.3/), you find yourself with an empty directory. The bucket ACL needs to be changed to support directory listing.

### Current behavior
The directory listing on downloads.newrelic.com is empty for any version of the CLI.

### Expected behavior
The released artifacts are listed in the directory.

### Steps To Reproduce
1. Browse to https://download.newrelic.com/install/v0.43.3/

**Comment by sanderblue** [comment]
Hi @grepory, thanks for reporting this issue! I was able to confirm what you've reported. We'll see what we can do 🙂
