### ISSUE TITLE
[Feature] Terraform: add widget_type validation support for widget_log_table

### ISSUE THREAD

**Issue by nunopi** [newrelic/newrelic-cli#1328]
### Feature Description
Add "logger.log-table-widget" / "widget_log_table" to the WidgetTypes map

### Describe Alternatives
No alternatives as far as I know

### Additional context
The validation for widget types is missing the widget log table type and as such, when converting a dashboard that contains this widget type to a terraform file, it fails with the following error:
`FATAL unrecognized widget type "logger.log-table-widget"`

Support for this widget type has been added recently to terraform-provider-newrelic here: https://github.com/newrelic/terraform-provider-newrelic/issues/1831

See proposed change here: https://github.com/nunopi/newrelic-cli/commit/f83fb89f41cf2bfb23e90b84bd5b17f0e921bcd7

**Comment by kidk** [comment]
I think your change looks good @nunopi 

Could you create a PR for it?
