### ISSUE TITLE
Enable non-fuzzy Entity Searching

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-cli#138]
### Description
The current implementation of entity search returns a set of fuzzy matched entities, which can make it difficult when you are trying to filter to a specific name.

### Acceptance Criteria
- Able to search on strict values (i.e.  `--name "webportal"` should hard-match)
- Ability to fuzzy search (Suggestion: use NRQL syntax for fuzzy searching: `--name "%webportal%"`)

**Comment by jthurman42** [comment]
User testing feedback actually preferred the opposite.  Default to fuzzy (like most cli tools do), but would be nice to enable some non-fuzzy syntax.  Unsure how we could do that since downstream is all fuzzy matching (without re-implementing our own search queries)

**Comment by lhenry7** [comment]
A name search would imply an exact match to me, or at least deserves the option to make it so.
