### ISSUE TITLE
Please provide an ARM64 docker image or a multi platform image

### ISSUE THREAD

**Issue by artlist-scottambrose** [newrelic/newrelic-cli#1518]
### Feature Description

The official newreliccli docker image on dockerhub only supports linux/amd64 https://hub.docker.com/r/newrelic/cli/tags. 

ARM64 builds are available https://github.com/newrelic/newrelic-cli/releases/tag/v0.73.3 but there's no official docker image with ARM support.

Having this officially supported would make using the newrelic cli on ARM machines with docker containers that little bit easier.

### Describe Alternatives

The alternative is to simply build my own image via downloading the appropriate binary from the github releases.

### Additional context

Basic scenario: Imagine having some ARM virtual machines that perform certain pipeline steps (self-hosted runners - GitLab, GitHub etc). There might be steps that want to use the newrelic cli (creating a change marker for a deployment for example). Having an ARM64 image or even better, a multi-platform image would make this scenario that little bit smoother by supporting a more diverse set of hardware configurations.

Thanks :+1:

**Comment by sanderblue** [comment]
Thanks for inquiry @artlist-scottambrose. This seems like a reasonable ask. I can't provide an exact timeline, but we'll see where we can fit this in. 👍

**Comment by dushanstoryful** [comment]
We also looking for ARM64 docker image
