### ISSUE TITLE
Create release process for publishing new releases to Snapcraft (Linux distros)

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-cli#168]
### Objective
We currently do not provide a way for Linux users to install the New Relic CLI from the command-line. GoReleaser supports [Snapcraft](https://snapcraft.io/) which is "The app store for Linux". It provides the ability to distribute a Go app that's "easy to discover and install by millions using the Snap Store or command-line every day."

Snapcraft also provides a ["First Snap" tutorial](https://snapcraft.io/first-snap#go) for Go to facilitate the process.

From GoReleaser:
> Snaps are a new packaging format, that will let you publish your project directly to the Ubuntu store. From there it will be installable in all the supported Linux distros, with automatic and transactional updates.

#### Utilize GoReleaser if possible
GoReleaser supports [generating `snap` packages](https://goreleaser.com/snapcraft/). 

From GoReleaser:
> Note that GoReleaser will not install `snapcraft` nor any of its dependencies for you. 

Also note that CircleCI provides their own [documentation for publishing snap packages](https://circleci.com/docs/2.0/build-publish-snap-packages/#section=deployment) as well. So if using GoReleaser proves to be difficult, we can go this route.

<br>

##### Examples discovered during research
- [CircleCI](https://github.com/CircleCI-Public/circleci-cli/blob/master/snap/snapcraft.yaml) utilizes Snapcraft in their [`.circleci/config.yml`](https://github.com/CircleCI-Public/circleci-cli/blob/master/.circleci/config.yml#L206-L224) to distribute their own CLI. 
- [Heroku CLI](https://github.com/heroku/cli/blob/master/snap/snapcraft.yaml) also uses Snapcraft in their [`.circleci/config.yml`](https://github.com/heroku/cli/blob/master/.circleci/config.yml#L153-L162)

#### Plan B
If GoReleaser won't work, Snapcraft has solid [documentation for publishing snaps](https://snapcraft.io/docs/snapcraft-overview).

### Acceptance Criteria
- Confirm RHEL and CentOS are supported 
- Publishing new releases to Snapcraft can be done via our CI/CD pipeline 
- Docs should reflect the latest information for installing the CLI via Snapcraft

**Comment by zlesnr** [comment]
https://github.com/newrelic/newrelic-cli/pull/193
