### ISSUE TITLE
Create release process for publishing new releases to Chocolatey (Windows)

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-cli#170]
### Objective
We currently do not provide a way for Windows users to install the New Relic CLI from the command-line. [Chocolatey](https://chocolatey.org/docs/CreatePackages)(cmd: `choco`) is a package manager for Windows. Unfortunately GoReleaser does not support packaging for Chocolatey, but we can grab the generated binaries to facilitate creating a Chocolatey package.

CircleCI provides a [Windows orb](https://circleci.com/orbs/registry/orb/circleci/windows) that includes Chocolatey, so this may help us with creating packages via `choco`. CircleCI's [Hello World On Windows](https://circleci.com/docs/2.0/hello-world-windows/) tutorial might also inform the beginning steps needed, although I think it's missing information related to Chocolatey since that's out of scope for that doc

The [Chocolatey Wiki - FAQs](https://github.com/chocolatey/choco/wiki/ChocolateyFAQs) seemed quite helpful for finding more information. Some examples are linked below.
- [What Are Chocolatey Packages?](https://github.com/chocolatey/choco/wiki/GettingStarted#what-are-chocolatey-packages)
- [What kind of package types does Chocolatey support?](https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#what-kind-of-package-types-does-chocolatey-support)

**Comment by zlesnr** [comment]
To be verified/fixed next release.

**Comment by zlesnr** [comment]
https://github.com/newrelic/newrelic-cli/pull/210
