### ISSUE TITLE
Spike: Determine how we can sign packages 

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-cli#171]
### Objective
We want all of the assets we produce to be digitally signed. We want to follow a similar process that the Infrastructure agent currently uses.

GoRelease seems to [support signing](https://goreleaser.com/customization/#Signing) via the `signs` config option, but might have some limitations (see bottom of Signing section).

**Comment by ctrombley** [comment]
Signed:
- MSI
- Checksums
- goreleaser archives

Unsigned:
- Snaps
- Homebrew kegs
- Scoop packages

The public key also needs to be published and made available somewhere.
