### ISSUE TITLE
Bad API Key Error

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-cli#191]
I am using the CLI through the docker container (newrelic/cli:latest). I have tried setting my API key and region using both the environment variables (NEW_RELIC_API_KEY and NEW_RELIC_REGION), as well as through `newrelic profile add`. However, I keep getting a mysterious error message:

> FATAL[2020-04-14T18:07:30Z] 401 response returned: Bad API Key or no API Key provided, null 

Using the exact same API key to hit the REST API via curl is working properly.

**Comment by jthurman42** [comment]
@rittneje Can you confirm that you're using a Personal API key and NOT an Admin API key?  The CLI leverages NerdGraph, the New Relic GraphQL API, which uses the newer API keys.

Personal API key docs: https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#personal-api-key

**Comment by rittneje** [comment]
Yes, that was the issue. Thank you!
