### ISSUE TITLE
newrelic cli commands need to be updated in the newrelic-cli/blob/master/docs/GETTING_STARTED.md.

### ISSUE THREAD

**Issue by sri-shetty** [newrelic/newrelic-cli#202]
### Description
The cli commands in the readme page https://github.com/newrelic/newrelic-cli/blob/master/docs/GETTING_STARTED.md all need updates.

### Go Version
Not Applicable

### Current behavior
I was able to find correct commands for:
1. Find application ID for your app:  newrelic apm application search -n <Your appName>
2. Create tag:  newrelic entity tags create --guid <your guid> --tag key:value
3. Add multiple tags: newrelic entity tags create --guid <your guid> --tag key1:value1,key2:value2
4. Read tags for the give entity: newrelic entity tags get --guid <your guid>
4. Deployment marker: newrelic apm deployment create --applicationId <your appId> --revision <app revision> --change-log <app changeLog> --description <change desc> --user <username>

### Expected behavior
Update readme document

### Steps To Reproduce
Not Applicable

### Debug Output (if applicable)
Not Applicable

### Additional Context
Not Applicable

### References or Related Issues
Not Applicable

**Comment by jthurman42** [comment]
Looks like this document wasn't updated with the last round of UX changes to the CLI, and should be easy enough to get resolved.  Also a great issue for the community to submit a PR.
