### ISSUE TITLE
--help should work without credentials/config/default-profile

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#33]
### Description
Currently, unless the three items above are set in the user environment, the user is unable to get help using the CLI.  We should improve the error handling here to give the user some next steps.  Also, we should document this in the README.

### Current behavior

Without this, `--help` fails with "no configuration found" and does not display the help.

### Expected behavior

`--help` for a new install should produce something useful for the user to get started.  Perhaps this means creating new configuration files.

### Steps To Reproduce
1. rm -rf ~/.newrelic
2. ./bin/darwin/newrelic --help

Related to #12

**Comment by jthurman42** [comment]
Fixed in #47
