### ISSUE TITLE
Spike a means of installing logging for linux from the CLI

### ISSUE THREAD

**Issue by ctrombley** [newrelic/newrelic-cli#403]
Blocked by #402.

### AC:
- Should occur as a post-install step after the infra agent has been installed

### Notes:
- [New Relic Logging installation docs](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#requirements)

**Comment by jbeveland27** [comment]
Initial recipe file: https://github.com/newrelic/open-install-library/commit/5befeee1dc27c9875afd9e067541de2701b76462
