### ISSUE TITLE
Simplify CLI config, profile, and credential management

### ISSUE THREAD

**Issue by sanderblue** [newrelic/newrelic-cli#458]
### Objective

Refactor configuration management (which currently involves 3 separate "objects") to use a single source of truth. The singleton configuration object can then be used to "get" and "set" configuration items such CLI options as well as profile and credential information. This will provide a simple, but flexible programmatic API for clean integration with new and existing features.

Dev Notes: Essentially wrap `*viper.Viper`

### Acceptance Criteria

- Our configuration object in code is represented as single source of truth
- Profiles and credentials can be updated via said single source of truth

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-71

**Comment by rishimukhop1** [comment]
The decision is that we are going to postpone working on this item for now, since it turned out to be more work than anticipated. We will revisit it later.
