### ISSUE TITLE
Create logs for installed integrations & instrumentation

### ISSUE THREAD

**Issue by rishimukhop1** [newrelic/newrelic-cli#490]
We need to have a local log file of all the integrations that have been installed.I think it would just be a perpetual log file that keeps track of everything executed during the install process, meaning it wouldn't be overwritten.

 If the installer is run again, we could consider putting that into another log file. In other words, each log file could be named something like NRInstallLog_timestamp and correspond to one "run" of the install.

Aha! Link: https://newrelic.aha.io/features/VIRTUOSO-92

**Comment by jpvajda** [comment]
updated with a few clarifying requirements.
