### ISSUE TITLE
newrelic-cli@0.18.2: hash check failed

### ISSUE THREAD

**Issue by dormanb2** [newrelic/newrelic-cli#507]
App:         newrelic-cli/newrelic-cli
URL:         https://github.com/newrelic/newrelic-cli/releases/download/v0.18.2/newrelic-cli_0.18.2_Windows_x86_64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    bd5d93bc6bcbcc92c191e1367aabdf198a5c45c4919e2affbca38cba22f7501b
Actual:      9ce3f8bce21c3a17d0fac594276ce5fe60f5f807c67b8f152e6179593bd5b942

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/newrelic/newrelic-cli/issues/new?title=newrelic-cli%400.18.2%3a+hash+check+failed

**Comment by ctrombley** [comment]
Hi @dormanb2 , the hash check is succeeding for me.  Can you share more information about your failure?

``` bash
$  gpg --verify newrelic-cli_0.18.2_Windows_x86_64.zip.sig newrelic-cli_0.18.2_Windows_x86_64.zip
gpg: Signature made Wed Dec  9 08:47:24 2020 PST
gpg:                using RSA key 86BE01DA9B1DA1FCF8281409DC9FC6B1FCE47986
gpg: Good signature from "Developer Toolkit Team <developer-toolkit-team@newrelic.com>" [ultimate]
```

**Comment by dormanb2** [comment]
Please close.  I will not being using this cli at this time.

 

Thank you,

-Byron-
