### ISSUE TITLE
Environment variables should override profile data

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#564]
Currently, when the CLI is run for the first time on a system, the profile setup looks to the environment variables to determine if the information required to setup a new profile is present.  In such a case, a new profile is created using the values from the environment.  However, future executions of the CLI will use the variables from the profile, even if the environment contains different values.  I believe the likely expectation from a user perspective is that an environment variable specified would override that which is stored on disk in the profile.

**Comment by sanderblue** [comment]
Hi @zlesnr! Hope all's well friend! 😎 Just doing some spring cleaning here and realized we're no longer automatically generating the config files for first-time usage based on environment values that are used inline. Unfortunately this behavior was not compatible with the `newrelic install` command that we 🐑 'd a good while back, so users will be prompted to use `newrelic profile configure` if they run into this scenario 🤷  Caio for now 🦙
