### ISSUE TITLE
Unneeded text in README.md for Chocolatey

### ISSUE THREAD

**Issue by kidk** [newrelic/newrelic-cli#702]
### Description
The [readme](https://github.com/newrelic/newrelic-cli/blob/master/README.md) states the following for Chocolatey, but it doesn't match anymore with the command below.

```
Currently the `newrelic-cli` is in review with in the Chocolatey system, and
should be published in the next few days.  That means that you must include the
version spec, as follows.
```

I wanted to double check if it's ok to remove? Happy to create the pull request.

**Comment by zlesnr** [comment]
Thank you for the note.  That does look like it needs an update, PRs welcome.

**Comment by kidk** [comment]
Pull request created 👆 Thanks
