### ISSUE TITLE
No such host error when using events post

### ISSUE THREAD

**Issue by jamesc90** [newrelic/newrelic-cli#713]
### Description
When trying to post a custom event to the eu region newrelic-cli is using an incorrect url.

```
c:\newrelic events post -a xxxx --event "{ \"eventType\": \"Payment\", \"amount\": 123.45 }

level=fatal msg="POST https://insights-collector.eu.newrelic.com/v1/accounts/xxxx/events giving up after 4 attempt(s): Post \"https://insights-collector.eu.newrelic.com/v1/accounts/2485343/events\": dial tcp: lookup insights-collector.eu.newrelic.com: no such host" 
```

### Version
0.18.25

**Comment by zlesnr** [comment]
This looks related to https://github.com/newrelic/newrelic-client-go/pull/678 which should have been released by now.

**Comment by jamesc90** [comment]
@zlesnr tested with version 0.18.29 and it works as expected.
