### ISSUE TITLE
Entity tags commands not consistent

### ISSUE THREAD

**Issue by mohan08pCimpress** [newrelic/newrelic-cli#717]
***Objective***
The entity tags commands are not consistent in producing output. Kindly, correct these to make it work as expected.

***Acceptance Criteria***

1. I tried with `newrelic-cli`  it’s doing the basic things as adding/deleting the tag. But, again I found a bug in there. When I added n number of tags to an entity e.g 3 tags and try to replace one of them, it will replace the value of that tag and removes the other two which is not consistent. So, I can not rely on it in my automation.
2. When I delete a key it will delete the value as well, as I see the issue has already created at https://github.com/newrelic/newrelic-cli/issues/144

**Comment by zlesnr** [comment]
Thank you for raising the issue.  Can you give example commands that you are using to reproduce this?
