### ISSUE TITLE
Manual/automated testing for 2-way config/profiles compatibility with NR1 CLI

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#73]
### Objective

To ensure confidence in terms of compatibility with the configuration and credential files from the nr1 cli.

### Acceptance Criteria
- A known good example of all configuration files is available for use in testing.
- Tests for each configuration file are present and the functionality of the config/profile loader works as expected.

**Comment by jthurman42** [comment]
We should be able to add downloading of the NR1 CLI to the make system for integration testing the two.
