### ISSUE TITLE
Chocolatey package is not updated

### ISSUE THREAD

**Issue by fv-ian** [newrelic/newrelic-cli#745]
### Description
Latest version of the chocolately package is 0.10.0 with 0.19.0 having been released already. 

### Current behavior
Many versions behind latest. 

### Expected behavior
Latest version of the chocolatey package is up to date with the latest version released by the project. 

### Steps To Reproduce
choco install newrelic-cli

### Debug Output (if applicable)
If applicable, add associated log output to help explain the problem.

### References or Related Issues
Are there any other related GitHub issues (open or closed) or Pull Requests that should be linked here?

**Comment by Julien4218** [comment]
Fixed
