### ISSUE TITLE
SuccessLinkType

### ISSUE THREAD

**Issue by crwecker** [newrelic/newrelic-cli#789]
Just started getting error when spinning up a new server using 
 ```
 curl -Ls https://raw.githubusercontent.com/newrelic/newrelic-cli/master/scripts/install.sh | bash
NEW_RELIC_API_KEY=### NEW_RELIC_ACCOUNT_ID=### NRIA_VERBOSE=0 /usr/local/bin/newrelic install --skipDiscovery --skipIntegrations --assumeYes
```

   _   _                 ____      _ _
  | \ | | _____      __ |  _ \ ___| (_) ___
  |  \| |/ _ \ \ /\ / / | |_) / _ | | |/ __|
  | |\  |  __/\ V  V /  |  _ |  __| | | (__
  |_| \_|\___| \_/\_/   |_| \_\___|_|_|\___|

  Welcome to New Relic. Let's install some instrumentation.

  Questions? Read more about our installation process at
  https://docs.newrelic.com/

  New Relic installation complete!
  Your data is available at https://one.newrelic.com/redirect/entity/
FATAL We encountered an error during the installation: there was an error discovering system info: could not retrieve process filter criteria: maximum retries reached: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Enum \"SuccessLinkType\" cannot represent value: \"explorer\""}]. If this problem persists please visit the documentation and support page for additional help here: https://one.nr/06vjAeZLKjP

**Comment by webnard** [comment]
If you specify an earlier version with an environment variable, you can get around this problem. Seems to just be for 0.20.28.

```
curl -Ls https://raw.githubusercontent.com/newrelic/newrelic-cli/main/scripts/install.sh | VERSION=0.20.7 bash
```
