### ISSUE TITLE
Homebrew recipe and associated docs

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#82]
### Objective
Homebrew users are able to install and learn about the CLI.

### Acceptance Criteria
- A brew formula is available to users
- Documentation about the brew formula is available to users
- Any caveats to using the brew formula are readily available to users of Homebrew

**Comment by jthurman42** [comment]
This would also require an automated build pipeline for the binaries (or at least Mac)

**Comment by zlesnr** [comment]
https://github.com/Homebrew/homebrew-core/pull/51015

**Comment by jthurman42** [comment]
Homebrew came back saying we need to make it build on the fly, the Terraform formula might be a good one to reference: https://github.com/Homebrew/homebrew-core/blob/9b33d0efa69172d6fb865b35d52a01b17098e863/Formula/terraform.rb

**Comment by ctrombley** [comment]
Resolved by Homebrew/homebrew-core#51015
