### ISSUE TITLE
Docker hub image and associated docs

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#83]
### Objective
A docker image is available for users to download and use.

### Acceptance Criteria
- A docker image is available
- Documentation about the use of the image and any caveats about the image are readily available to the user.

**Comment by jthurman42** [comment]
We already have the ability to build the image, just need to configure CircleCI to do so and push.

**Comment by jthurman42** [comment]
Resolved in #93 and Docker Hub repo created: https://hub.docker.com/r/newrelic/cli
