### ISSUE TITLE
Command contract refactor

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#86]
### Objective
Conform to words and style that are less offensive to the team.

### Acceptance Criteria
- Verbs after nouns
- Prefer subcommands over hyphens
- Eliminate use of “describe”
- “Add tags” rather than “create tags” (follow what is in NG)
- Determine a name for the CLI command and rename if it’s changing from “newrelic”

**Comment by ctrombley** [comment]
Resolved by #119
