### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by ronandoolan2** [newrelic/newrelic-cli#887]
### Description
I try to run newrelic-cli.newrelic apm application search and get panic: runtime error

### Go Version
go version go1.16.3 linux/amd64
This was installed via snap

### Current behavior

panic: runtime error: invalid memory address or nil pointer dereference         
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa426ca]         

### Expected behavior
Display list of apm applications

### Steps To Reproduce
1. Set api key
2. run ` newrelic-cli.newrelic apm application search`

### Debug Output (if applicable)
panic: runtime error: invalid memory address or nil pointer dereference         
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa426ca]         
                                                                                
goroutine 1 [running]:                                                          
github.com/newrelic/newrelic-cli/internal/apm.glob..func1.1(0xc0000d4000)       
        /home/runner/work/newrelic-cli/newrelic-cli/internal/apm/command_applica
tion.go:78 +0x38a                                                               
github.com/newrelic/newrelic-cli/internal/client.WithClientFrom.func1.1(0xc00024
ec30)                                                                           
        /home/runner/work/newrelic-cli/newrelic-cli/internal/client/helpers.go:2
5 +0xb8                                                                         
github.com/newrelic/newrelic-cli/internal/credentials.WithCredentialsFrom(0xc000
02a510, 0x2b, 0xc00027dc40)

**Comment by zlesnr** [comment]
Thank you for the report.  What version of the CLI do you have to produce this error?

**Comment by ronandoolan2** [comment]
newrelic version 0.28.0
I tried a few different versions and got the same behavior

**Comment by zlesnr** [comment]
Can you provide the full command output, obscuring any secrets and include the `--debug` flag please?

**Comment by ronandoolan2** [comment]
No debug flag for that command
```
newrelic-cli.newrelic apm application search --accountId ******* --name "******" --debug
Usage:
  newrelic apm application search [flags]

Examples:
newrelic apm application search --name <appName>

Flags:
  -h, --help          help for search
  -n, --name string   search for results matching the given APM application name

Global Flags:
  -a, --accountId string    A New Relic account ID
      --applicationId int   A New Relic APM application ID
      --format string       output text format [JSON, Text, YAML] (default "JSON")
  -g, --guid string         search for results matching the given APM application GUID
      --plain               output compact text

FATAL unknown flag: --debug 
```

**Comment by zlesnr** [comment]
Ah my mistake.
