### ISSUE TITLE
MacOS: "This software needs to be updated. Contact the developer for more information."

### ISSUE THREAD

**Issue by Gene5ive** [newrelic/newrelic-cli#888]
This results from trying to run the New Relic CLI installer:

![image (1)](https://user-images.githubusercontent.com/4206754/120696739-bd326380-c461-11eb-8179-585d0e29af6e.png)

**Comment by zlesnr** [comment]
Hi, thank you for the report.  Can you tell me where you got the installer file you are opening here?

**Comment by Gene5ive** [comment]
@zlesnr From the 'Download installer' button on this page: https://one.newrelic.com/launcher/developer-center.launcher

**Comment by zlesnr** [comment]
Thank you for the report.  This is an issue for one of our other CLIs, but in this case it isn't open source.  I'll let the team know.
