### ISSUE TITLE
Tutone Generation GH Action is broken

### ISSUE THREAD

**Issue by jthurman42** [newrelic/newrelic-cli#922]
### Description
Build system: Tutone generate looks to have never worked.

https://github.com/newrelic/newrelic-cli/actions/workflows/generate.yml

Fixing the script (update build/generate.mk to fetch tools before running tutone) causes generation to work, but appears that there are a fair number of manual changes, specifically adding `yaml` tags that would be broken.

I suggest one of the following:
* Fix generate to run and make correct tags
* Disable the generate GH Action

**Comment by ctrombley** [comment]
We need yaml tag generation support if this is going to be useful for us, so I am in favor of disabling the action and generating manually until that can be added to the tutone library.

**Comment by Julien4218** [comment]
Tutone GH is now working, we may look at making this action run on-demand in the near term.
